---
apiVersion: v2
appVersion: 10.0.1
description: seafile helm package
name: seafile
version: 5.1.0
kubeVersion: ">=1.22.0-0"
keywords:
  - seafile
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/seafile
icon: https://manual.seafile.com/media/seafile-transparent-1024.png
sources:
  - https://github.com/haiwen/seafile-docker
maintainers:
  - name: c0ffee
    email: 1407812+c0ffee@users.noreply.github.com
dependencies:
  - name: common
    repository: https://c0ffee.github.io/helm-charts
    version: 1.2.0
  - name: mariadb
    version: 11.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - condition: memcached.enabled
    name: memcached
    repository: https://charts.bitnami.com/bitnami
    version: 6.3.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Updated app to seafile 9.0.10
